CREATE DATABASE PRUTCL;
USE PRUTCL;

/*
	DDL - DATA DEFINITION LANGUAGE (CREATE, ALTER, DROP, ... )
    DML - DATA MANIPULATION LANGUAGE (SELECT, INNER JOIN, GROUP BY, INSERT, UPDATE, DELETE, TRUNCATE, ... )
    TCL - TRANSACTION COMMAND LANGUAGE (BEGIN, SAVEPOINT, ROLLBACK, COMMIT, ... )
    DCL - DATA CONTROL LANGUAGE (GRANT, REVOKE)
*/

SHOW GLOBAL VARIABLES LIKE "AUTOCOMMIT";

CREATE TABLE ALUMNOS(
	CODALU INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE CHAR(100),
    FECHANACI DATE,
    ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NOTAFINAL DOUBLE
);

CREATE TABLE NOTAS (
	NOMBRE CHAR(10)
);

SET SQL_SAFE_UPDATES=0;

SELECT * FROM ALUMNOS;

TRUNCATE ALUMNOS;
DROP TABLE ALUMNOS;
DELETE FROM ALUMNOS WHERE CODALU=5 AND CODALU=3;
UPDATE ALUMNOS SET NOTAFINAL=10.0 WHERE CODALU=2 AND CODALU=3;

/* EJEMPLO TRANSACCIONES */
SET AUTOCOMMIT=0;
START TRANSACTION;
BEGIN;

INSERT INTO ALUMNOS (NOMBRE,FECHANACI,NOTAFINAL) VALUES
('PEPE','2001-10-10','8.5');
INSERT INTO ALUMNOS (NOMBRE,FECHANACI,NOTAFINAL) VALUES
('PEPA','2000-11-15','9.5');
INSERT INTO ALUMNOS (NOMBRE,FECHANACI,NOTAFINAL) VALUES
('PEPITO','2020-11-15','10.0');

SAVEPOINT PEPA;
SAVEPOINT PEPITO;
SAVEPOINT NOTAS_UPDATE;

ROLLBACK TO SAVEPOINT PEPA;
ROLLBACK TO SAVEPOINT PEPITO;
ROLLBACK TO SAVEPOINT NOTAS_UPDATE;

ROLLBACK;

COMMIT;

/* 
	EJERCICIO PEPOITE 
    - INSERTAREMOS PEPE (2 VECES) Y GRABAREMOS UN SAVEPOINT PEPA
    - INSERTAREMOS PEPA (2 VECES) Y GRABAREMOS UN SAVEPOINT PEPITO
    - INSERTAREMOS PEPITO (2 VECES)
    
    - HACER ROLLBACK TO SAVEPOINT PEPA
    - HACER ROLLBACK TO SAVEPOINT PEPITO

*/




















