/* DCL - GESTION DE USUARIOS */

CREATE USER PEPE IDENTIFIED BY '12345';
CREATE USER PEPITO IDENTIFIED BY 'AAAA';
DROP USER PEPE;

SELECT USER();
SELECT * FROM MYSQL.USER;

FLUSH PRIVILEGES;
SHOW GRANTS FOR PEPE;

GRANT ALL PRIVILEGES ON *.* TO PEPE;
GRANT ALL PRIVILEGES ON JARDINERIA.* TO PEPE;
GRANT SELECT, INSERT, UPDATE, DELETE, DROP ON ACADEMIA.* TO PEPE;

REVOKE ALL PRIVILEGES, GRANT OPTION FROM PEPE; /* QUITA TODO LOS PRIVILEGIOS EN TODO LO ASIGNADO */
REVOKE INSERT, UPDATE, DROP ON *.* FROM PEPE;
REVOKE INSERT, SELECT ON JARDINERIA.* FROM PEPE;

GRANT UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, 
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER, DELETE ON `jardineria`.* TO `PEPE`@`%`
